version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      prod-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '*discord*'
          - '*prisma*'
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '*prisma*'
      discord-dependencies:
        patterns:
          - '*discord*'
      prisma-dependencies:
        patterns:
          - '*prisma*'
