apiVersion: v1
kind: Secret
metadata:
    name: avicii-secrets
    namespace: discord-bots
type: Opaque
data:
    discord_token: ENC[AES256_GCM,data:Bs76JFdbWmrbuu/gzcgFsi37Nc2HKejniZEvC8NR+WlgbMJY79sSgs/GxDInAW4zCHyeBwENOJUp24Js8D6BSG6zxC39/cGsPHnpRBuZFYrIVVR2Ffr2k0XfOdBMN9Wz,iv:LRWrTnKjrdVK7EyCcHmNXu5iHw6zdEnUOzHN6Xamwzs=,tag:+G9yZiXgXM8YWrvmasG7sg==,type:str]
    postgres_url: ENC[AES256_GCM,data:ByQNeNivTcvz6qYAY2+Wq1l+IxL2GXl6NJggTPzqvdbcq20tlFURgcZkwNKytMq+7Vu6HztiPuuj82LMjLSdZ5ISjzZwfsHAvGMXAjsreBTT1Ypt9ZROCN3yP6HUrlKj/Avip2A+poTP6KMnJH+2aw==,iv:Ak7jbhbDQQSfzHKV+aMN1rdl/0JPHd4QUAF/p837xUU=,tag:DEqG5YBmQzNP7KbrZnNjoA==,type:str]
    spotify_client_id: ENC[AES256_GCM,data:EvteFQIPOBKPWDIRy/ZMURlgXO3zMT1jK6z/iyuTAJiqU5SjWyOIIxEZaGE=,iv:Rah2PHS+Oz1HiIjyD9zHFvgE02C3FJysO2Mx9gXao1M=,tag:G1nt6182I/Fy4SqHEhPqtA==,type:str]
    spotify_client_secret: ENC[AES256_GCM,data:GFbB10UlD1Dd45vUILZKcmQtbKWceev+TJ19zxZiP3AyUm+qqHC8hm+fkrY=,iv:hrUcTwfzKhfLKvU5XDV4bvPgivLEQck2VKLVD2oHhfg=,tag:dxEfrxD6jFjLOpTiix/Vvw==,type:str]
    youtube_token: ENC[AES256_GCM,data:JHYem6QU1KAux5Ee481rDZ152d6YANV8rV+cBvn65dctT+/Q9MP0l3zaIAyFx42c1aoiMg==,iv:SbRtGd0gHES76JUuesi2TCDLZDXBMMggVvSbImpHi2c=,tag:QJzwHRPfB+wXHZdsiCWVGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-18T18:20:40Z"
    mac: ENC[AES256_GCM,data:CIe+4C3YtVO3Nd8JTI+c2JF4Ee5fsJblLnLXioBIqgV9S4f0Cn6+ZA6MJSOXa9J50cyXrGjSikxCCXbNb9JVX+mT5OZn+TIXYm9y/ODTSww82IHmByTEWyPZxu8Ajf/1+88MQAxRCcdlaMno9eq3PuHoT23B/KYr9EDu4+b8/jk=,iv:NWWRlmlslFOHw+QUiwx5ac0f9a+WH/pfIjxX9Lk6g6Q=,tag:GpPRw1OPgJkBc2+457PM1Q==,type:str]
    pgp:
        - created_at: "2024-05-18T18:20:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwYQawvj2xy7AQ//RvYlmivLsPDB/FncY3paiOq+sqYX5hmVTxedTTbe7A0W
            CBaYKryC/qrTSZJAplW0fTBRADejgm3QXOxYLj2bvyLYWtVzqNwW3gBspK+pAIIW
            KG6lJyQk1swJZAWaQPPJmrymMakvMfuQd7lfwI1dcOjJ1v8NHZRkmxzeWRUZg43e
            zAOdp/UHU90kMApvquiiMWrmEFwXExP/80aODu20sB5E+HFjKSch8amydabs9ekb
            wxiSXngum972AXrEs1KxQLh6s1APTzW7MOtao0RTsaxhSX0B3MgcSrzuzmSWwgML
            wPTHkb4zlnBVsC9GbTOMoi28ku6N5GGp8t8XxZSofWHlmuKON9nzdpfY7rpXfzNp
            AgGOEP0sbCK6/BCk63ACjEiR2IUbzsidR83+UaXF6+rs0Qgq4ai6wU26P3Etmk45
            97SPslYO0Sv3YzYOGarICvUMwBgrP1JuO1n8bvOyTngEPWeMLj8V2Igs4eYR7cKu
            FAEUNjg1C7g0FsAm4FCm/NO0q0YksPYxp0mBV0Pcz8082jydPwyXzvLRJIJSeuDi
            hwrbWgVoxi2IWiVE3reJT7Tp2aVWyy3Bp6+24+mUJyPV1JpcozUNq7S1/ds/5EN1
            QymF2SKrFBHJ85mFcOJttpPgjJauLn7LaS/nqSgmcvCpEsfTkWRKIY0kyetvfZvU
            aAEJAhDCMX38I9wz5xBxzStAcC37FSEZIZU4s18ROPUcxn6+IJ0yDKPOHUqSVeRM
            eDNmGP9pVF6uuY7xJrNSJKEWWxy/LJcQkeKSclxAEH3OgBDnmsbv81a8DDY87H8F
            /oyKgae3CX1E
            =FGOc
            -----END PGP MESSAGE-----
          fp: A0334AABC84DBCEBA32007A0216EC01EA61C8C77
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
