apiVersion: v1
kind: Secret
metadata:
    name: avicii-secrets
    namespace: discord-bots
type: Opaque
data:
    discord_token: ENC[AES256_GCM,data:MSfoQf3Cm13T2ylbGUEuGmBz6DT0Tu/wE1jGVtX9684hfuu57+GUUv/2PdL+9qkECgSiIxWHSX95mezECvL4/wj0o53cOz5c27TeL37L2QTN7yC3B20XR7mcXMsVR++7,iv:uY5rihkviZzy1OamzvFz2brl6dmbQjjdiD63WNBzvw4=,tag:lltUPljiN4v47SubLo5+2g==,type:str]
    youtube_token: ENC[AES256_GCM,data:VFCtWhmLpxqGwyKsxfjYKysucwrOg1AVdgnFOEMagF1X0aw8O9i/taD0mCtT414wHxDgPA==,iv:l4lC3L3eONOq67C1s6O3gpMEom6F3mM1Vt8rDuaEXNU=,tag:m5gMk0wRwQEJhWKECH8amw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-11T20:58:24Z"
    mac: ENC[AES256_GCM,data:wTHTwFmyYGbD3C6Jj1uJDWIgx7s9HMuZ65BwmTbaZV8/0hwAPO9Vko8uBWZfNQx19gxN+gJmcHl1IppW9YDilhdJE6wSumiQ2Opn90FpwH201nLDIXjQz3BE/PHB6Lb5bbsj+5uGx0+vaiRY0/N7A3euXDneLQIHOu9zyIDP5gE=,iv:fLFj3nbvJz3XkJ0O62J2P1BqH/X9ZTpWhNhDQ8zw56A=,tag:aS+f3KbWEmXFyxqpR1BnjQ==,type:str]
    pgp:
        - created_at: "2024-05-11T20:58:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwYQawvj2xy7AQ//aYLlT0+KQJz4QD8TTJ3E9CGgVhe/v6HOw4JK4cd7nIZp
            SfxrjtwAsTRi7UO2yB/3xMLMoh+Lu+x7CR167+zWpRI+2Wux99WbNC8wkVn3hkcU
            C0Zw+7M0ogFQm28d/laze9nA+IouGoxTnH7aThVa05nkrjddyDp1OA7wIAltnPPT
            poaTKk69u/WHo2gOpmhdNNjKRApv/eYyulETB+snWYvlSZL58xXfST6g9sPK6T2b
            cKOt116PxCYNl31F6IMdi2nLfLrJ7rYZ5fRkr5fqZFtSnwEb3pmMVR+RTVsm0gwo
            UYIlYhqRbMnvkQp1xk5OVJ5u8FtdVudKKAw71kcc2aAHgxAFzmQoeyJzdWF7fPAP
            x0FaFIcQIvs2ikRZSYnhhMq23uur8zCcBLFEGY0bQhniXgxgotNI1bs4+Zh/lAd+
            mZismlV/al0iW+AuP6X4IFsAK8GxKEgUFRmfzMN2kpk0Ct5BPfurFATHVjBMP4iV
            2XnY7ClIgvfRlc8GbJzLZLHlfyllnwTgX7DqT4MkR55wZklgYQpTb/xyPEHUsU+q
            rkD1OeCbdav4boiQXtrODh3eMU9/idfhY5cN9LsCpOdzCbSSRL/8hFKXHOfaCzqK
            Hwf/J3FpblMzMb5ar2TnAK+nmjFlGERTSu+DYslBk5SxPxNnrN836JRcCYZB8GPU
            aAEJAhA9D21DAcBxfwmTnQZQdf6ejMre+f+Vq5mrLSDwmcKW765L1i8W+O/zCQRq
            97xoJQBqGrUGasPeyS3KMHrl6P0DKwo4mg5dIETHo7EwdWmjVvMVR6Q2g6jOWGPr
            2waTlWkzBhsU
            =8+Hb
            -----END PGP MESSAGE-----
          fp: A0334AABC84DBCEBA32007A0216EC01EA61C8C77
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
