apiVersion: v1
kind: Secret
metadata:
    name: avicii-secrets
    namespace: discord-bots
type: Opaque
data:
    discord_token: ENC[AES256_GCM,data:iWAN0sB3IAknPYvyLJF+I8lT66qLXUReQzxAji6vzqjQYmSOs9NL61pMZ2mUgPXR6HL91pxMwGU2FGj4jbtyMM/HmoIGnT35I2je0lIDZs9HbJxjqzF+tl6Nsjudsrt2,iv:7/yxZoghaNcKj1pylziqPp4Z4xJ5Ne8t4uBnrOfuoUM=,tag:IUA7/5LId6IuQ91GJMW33A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-03T06:39:35Z"
    mac: ENC[AES256_GCM,data:tSL+HQ4cVsJM7n0HmVkGV5eLrVwr1u8iLtq7W7U4HoU4D0HYWUaZ8Us9a+vGaTFuSiKUvPs6SuDQbuWHIIFEDO+pGxCtvGWZvjV6byx3EgOUtIP686FBLr0CAIihmmHu+Ao2LD8njLyQbFFKvJs2WZ62EkIJCxrg9lsZsjqNCNw=,iv:TJBUf0vGeGuG7RB/EGn55RV8wSL+W5BAYbSC98jU23M=,tag:vQsPOLoEpnPgtu8ObR8Xiw==,type:str]
    pgp:
        - created_at: "2024-05-03T06:39:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwYQawvj2xy7ARAAgBPvT+UhuIxXR2ujXIJK+fFXaJ1y7yBYtxzEsgGny/k7
            RoEuHx70+c4AU4+mRQ9PYcGS9YnJTGOS+i9qH69rT5c4M55hnyINYH1PE0/XGLU7
            EbCjfL1reGRYOI5ESAkEotW9baGQvLz/qs+ZePppqOK0yOcmlKmB0HqKxXHgRGm4
            KhRUegRWsuwGcab5IehpCzet5luS0D60XCuq5b7ptJhGLriK+KOkmhnby1E6WjzV
            Bex8u9T2B9UMb4qe+l2FOj8x7vrvuVOdCoy+EsnlCWVq08WlSCWQ8NnNokapyswg
            D6zO3m01zaBcrh136nn8l6XFzBXJN2QKevUDYiz8WTvqLeL5+dgOfFh0JSMpcAui
            IQETVdQ99CxkNjAftNVQykQcDA1r7XqJ49xfe+0I+Oh6nu+DwIIf/RWehFIhPu1j
            AICpoQqPC0vaj75+aV1Ok0EPHJTsMf00P45flcI4T3rEc/5LlNDzBusNHNif2icM
            /g0Je8EcTYN+yWL30lhkTcByBuTsWe5CTrfmybOXJGZdvX3WJHM5frAddqzLXhQ7
            rAMH4AE6SjUXw4dEAh9QswycVEfJRH9IfAo8q02kCE5hbRETnP8YPmlCFPndfE+9
            r4D00a3ugaAf5V6BgqA/txeq2lKpt1WCEPf59racahMci93rmr1BRo+aHpI19LPU
            ZgEJAhA0Q0Vhw3dAqKMHY3PYafoZHJnWsU/U7QFe7VdIveu/rIM38nyGxnxj3VTd
            E/MauRprY6aZMz2uOMx6eRmzfd/yZjI19yYf2ylWRIVbvrB1NX7CXTAZ/AFieN9m
            kCej5RhZ5w==
            =mN6e
            -----END PGP MESSAGE-----
          fp: A0334AABC84DBCEBA32007A0216EC01EA61C8C77
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
