apiVersion: v1
kind: Secret
metadata:
    name: avicii-secrets
    namespace: discord-bots
type: Opaque
data:
    discord_token: ENC[AES256_GCM,data:2SDsTbBx9uz5ED8UXEdq8/pHIo7D0+3eh07RtW3fKp/tt6K14m0PaWHtYDoWEpUuEAfFOh8SnpunZrsDQ5KFyCvx/rcnQMXsU/P/IA3DAZhsklCM/5LBMY5UGL4HeiAM,iv:qT5v/kM/yjUKZ5FoCOraboyiXqumr7P3jpeTX8Rie/w=,tag:cpNeijLDAjxWOtoerUvOSQ==,type:str]
    postgres_url: ENC[AES256_GCM,data:GImH1rWQFAClcHg8QZOXIFByRld0BM7V2IBXYniSUBwZk7Cyn7kIUgOZBCgpUBDIq6bjqrX06I6MWl7EJGiYa59WBRsT/ZOlry8fm0aOaSGPJRyApR11qLR/Hxy4uNv8ipVNUmvPchYPOffYHh45RQ==,iv:XiwPxL1ol0FyfeXLgdq9WU6pgSbtdNl45nj7KVKpF3g=,tag:PrFVrwjA2GserOujlE4qhg==,type:str]
    youtube_token: ENC[AES256_GCM,data:Z2PQUh+yd4wgF2b6IWzdpyskFA5Qs7q3D/GDCOhdv12vDKf1ISEEqowz2r5IJVWvrUxUiQ==,iv:wAtBEQ+AWFgbQnjAFnMV5gZiexOoWZZJln1cTNCDHYo=,tag:SilpE8tUOmliOMOxTA+43Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-17T17:44:31Z"
    mac: ENC[AES256_GCM,data:djlvAXPLTGyLMO7ECIxfiAGsgEVx6QO7FipWNCPAuUq4JRzsKwYY+B77qI6/433i1h44FbklRoTf+rMvaH9gi4spEV3M8kQZctKy2Umjob8qyM6a6Y5W5TO/D0l3MFpmPSr8xLNdAK+2f+T4SZCG2KQPP9u2Gl63B9cBjcXHeJE=,iv:VUjWGsw7mRNEuIbxiDtS677Sj59itLBsE1Mb/6PLplg=,tag:ofh+BoDf7zPfLn1/vSK+TA==,type:str]
    pgp:
        - created_at: "2024-05-17T17:44:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwYQawvj2xy7AQ//abZ0AmxoG3No2oXIziAPU24UG0pborl2YVJadm25ieeJ
            1V95+1+b7EUe8Li5+foC67OsOXWPK5DSlk5USkah0srTYk0+oFnqO1QapAg5arl/
            rS9Kee+OTY3nnIqrZNb1NZUqx2p7bTfrZzEQh4UPR3wFDzO7uxOcjAAoiwX3hqAn
            4+DE+vjSn8yBadTa3Yha4lBpSkvZvQFvvnoRzI7m8y5SrOzyghSwfSpnx1yFC9F0
            Kh7luq68GSiTS03FyqccBsK8k9A8P1d35FlZVFsuO/Dw6OGLV8uoB25dElxjRfGh
            KFrC1ROdki8N16GFyJ/q76PZpNZ9hQDWEu0HvO8yXAjLFtun7PZbYe18nYCWgR94
            DM9ofI1HA9CdM5qJMM+SSmLhp26pzM5OeNy3pjE2KXKq3nfnycQODVeJKWp454yj
            2M5MTdfa0CL0hLa8e9GaXEMtOKQveRTtLmQ0jlgLZrobhxL0P7uYot5JPZPaKLE2
            agOJXiC3CtxVI5+/fIiaZ/AfezGS0JqH8+HWXfyhUsLcfj0MYPuphn1M4M8GdMWn
            rJGXMvnGTF1KOAgAHZCVK9MFYUHbpYzpu2km1hsyHxwnzVL5kg5U4clRVfXK5MQ3
            2wkZwdqIgtvDH+tENQLKfbh32JUUW172X7AeBdQQc1w+6AdZH7Q1I8JQGAKUu/DU
            aAEJAhA1A9yBmRrNee5m8RUBJkC2gZ7N5Z72NlqseHUBqK0t+19NfZx9q8G/qXQP
            gTHLnWf+O/OwWQfWED2qTE1+ZCaB/Y32FVdpC35Bwefnzu/xfuYWN9/OaqAKVtXC
            Cx6Nd6ALsA59
            =U8tC
            -----END PGP MESSAGE-----
          fp: A0334AABC84DBCEBA32007A0216EC01EA61C8C77
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
