apiVersion: apps/v1
kind: Deployment
metadata:
  name: avicii
  namespace: discord-bots
  labels:
    app: avicii
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: avicii
  template:
    metadata:
      labels:
        app: avicii
    spec:
      terminationGracePeriodSeconds: 600
      containers:
        - name: avicii
          image: ghcr.io/kylerichter/avicii
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: discord_token
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: postgres_url
            - name: YOUTUBE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: youtube_token
            - name: SAMPLE_CONFIGMAP
              valueFrom:
                configMapKeyRef:
                  name: avicii-config
                  key: key
          volumeMounts:
            - name: avicii-config-volume
              mountPath: /app/volume_mount/sample-config
      volumes:
        - name: avicii-config-volume
          configMap:
            name: avicii-config
            items:
              - key: sample.json
                path: sample-config.json
