apiVersion: apps/v1
kind: Deployment
metadata:
  name: avicii
  namespace: discord-bots
  labels:
    app: avicii
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: avicii
  template:
    metadata:
      labels:
        app: avicii
    spec:
      terminationGracePeriodSeconds: 600
      containers:
        - name: avicii
          image: ghcr.io/kylerichter/avicii
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: discord_token
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: postgres_url
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: spotify_client_id
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: spotify_client_secret
            - name: YOUTUBE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: avicii-secrets
                  key: youtube_token
          volumeMounts:
            - name: avicii-cache
              mountPath: /app/cache
              readOnly: false
      volumes:
        - name: avicii-cache
          hostPath:
            path: /mnt/vm-cache/avicii
            type: DirectoryOrCreate
