name: GitOps Deploy

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KUBE_CLUSTER: k3s
  REPO_NAME: avicii
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ github.sha }}
            latest

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && true || false }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main'
    container:
      image: ghcr.io/kylerichter/gitops-helper:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy with GitOps
        run: python /app/app.py
